Lanscape + Buttons
oroom/easyCalc pull request #13
Opened 2017-12-03 23:23 UTC by Siauruk

Landscape was fixed + few new buttons in landscape mode

2017-12-05 11:52 UTC, oroom requested changes

2017-12-05 11:52 UTC, oroom commented on Calculator/Calculator.swift
> +    func log(_ first: Double) -> Double{
нужен пробел после возвращаемого типа (в других функциях тоже)

2017-12-05 11:52 UTC, oroom commented on Calculator/Calculator.swift
> +        return result!
Предлагаю попробовать сделать result не Optional свойством вообще. Большого смысла result = nil не несет.

2017-12-05 14:30 UTC, oroom commented
@Siauruk Fix conflicts also, please

2017-12-07 13:37 UTC, artyomsadyrin commented on Calculator/Calculator.swift
> +        return result!
@oroom изменил это в своих последних коммитах

2018-04-29 03:46 UTC, closed without merging