Added optional binding everywhere
oroom/easyCalc pull request #16
Opened 2017-12-06 20:21 UTC by artyomsadyrin

2017-12-06 23:12 UTC, oroom requested changes
по enum не обязательно переделывать, но можно попробовать.

2017-12-06 23:12 UTC, oroom commented on Calculator/ViewController.swift
> +        if let tempResultNumber = resultArea?.text, let resultNumber = Double(tempResultNumber) {
`resultArea?` по идее оно уже force unwrapped.

2017-12-06 23:12 UTC, oroom commented on Calculator/ViewController.swift
> +        guard let button = sender as? UIButton else {
Можно переделать action на типизированный

2017-12-06 23:12 UTC, oroom commented on Calculator/ViewController.swift
> +            case "+":
Можно переписать с учетом того, что мы разбирали про enum на последнем занятии (инициализатор с rawValue).

2017-12-07 08:38 UTC, artyomsadyrin commented on Calculator/ViewController.swift
> +        if let tempResultNumber = resultArea?.text, let resultNumber = Double(tempResultNumber) {
Да, чего-то не заметил.

2017-12-07 13:12 UTC, artyomsadyrin commented on Calculator/ViewController.swift
> +        if let tempResultNumber = resultArea?.text, let resultNumber = Double(tempResultNumber) {
Хотя если писать просто `if let resultNumber = Double(resultArea.text!)`, то будет ошибка. А если оставить как есть `if let resultNumber = Double(resultArea.text!)` разве не будет force unwrapped?

2017-12-07 13:15 UTC, artyomsadyrin commented on Calculator/ViewController.swift
> +            case "+":
Как это можно сделать, если входной параметр (+, - и т.д.) не равны объектам в enum (plus, minus и т.д.)?

2017-12-07 13:16 UTC, artyomsadyrin commented on Calculator/ViewController.swift
> +        guard let button = sender as? UIButton else {
Не совсем понял, что это значит. Написать, чтобы функция принимала тип UIButton вместо Any?

2017-12-08 08:58 UTC, artyomsadyrin commented on Calculator/ViewController.swift
> +        if let tempResultNumber = resultArea?.text, let resultNumber = Double(tempResultNumber) {
@oroom Похоже, что Xcode по-другому не принимает. 😧

2017-12-10 15:15 UTC, oroom commented
@artyomsadyrin Fix conflicts please

2017-12-10 21:30 UTC, artyomsadyrin commented
@oroom разрешил конфликт

2017-12-11 14:52 UTC, merged